#!/bin/bash

PEBBLE_PATH="/usr/share/pebble-sdk"
BIN_PATH="$PEBBLE_PATH/bin"

export PEBBLE_TOOLCHAIN_PATH="$PEBBLE_PATH/arm-cs-tools/bin"
export PATH="$BIN_PATH:$PATH"
export PYTHONHOME="$PEBBLE_PATH/.env/"
if [ ! -e "$PYTHONHOME" ]; then
	echo 'You must set up a virtualenv before you can use the pebble tool.'
	echo "Try these commands from $PEBBLE_PATH:"
	echo
	echo 'virtualenv --no-site-packages .env'
	echo 'source .env/bin/activate'
	echo 'pip install -r requirements.txt'
	echo 'deactivate'
	echo
	echo "If you don't have 'virtualenv', try \`sudo pip install virtualenv\`.'"
	echo "If you don't have 'pip', try \`sudo easy_install pip\`."
	echo "If you still need help, contact devsupport@getpebble.com."
	exit 1
fi

export PHONESIM_PATH="$PYTHONHOME/bin/pypkjs"

"$PEBBLE_PATH/.env/bin/python" "$PEBBLE_PATH/pebble-tool/pebble.py" "$@"