#!/bin/bash 
version="4.4-rc1"
destination="/usr/share/pebble-sdk"

if [ $(uname -m) == 'x86_64' ]; then
  bitness="64"
else
  bitness="32"
fi

rm -rf $destination

dir=`mktemp -d` && cd $dir
wget https://dl.dropboxusercontent.com/u/20902550/pebble-sdk/pebble-sdk-$version-linux$bitness.tar.bz2
tar xf pebble-sdk-$version-linux$bitness.tar.bz2
mv pebble-sdk-$version-linux$bitness $destination

cd $destination
ln -s /usr/share/pebble-arm-cs-tools arm-cs-tools

pip install -q virtualenv
virtualenv --no-site-packages .env
source .env/bin/activate
pip install -q -r requirements.txt
deactivate

rm -rf $dir